name: Dependabot automation merge

on:
  # Dependabot が作成した PR に対してのみ実行する
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true

permissions:
  pull-requests: write
  contents: write
  issues: write
  repository-projects: write

jobs:
  dependabot-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 13
    steps:
      - name: Check event and actor
        run: |
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]] && [[ "${{ github.actor }}" != "dependabot[bot]" ]]; then
            echo "The event is not workflow_dispatch and the actor is not Dependabot. Exiting..."
            exit 0
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'topic/dependabot'
          fetch-depth: 0
        if: github.event_name != 'workflow_dispatch'

      - name: Fetch PR data
        id: pr_data
        if: github.event_name == 'workflow_dispatch'
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query ($owner: String!, $repo: String!, $prNumber: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $prNumber) {
                  author {
                    login
                  }
                  title
                  url
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          prNumber: ${{ github.event.inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR was created by Dependabot
        id: check_author
        run: |
          if [[ "${{ steps.pr_data.outputs.data.repository.pullRequest.author.login }}" != "dependabot[bot]" ]]; then
            echo "PR was not created by Dependabot. Exiting..."
            exit 1
          fi
        if: github.event_name == 'workflow_dispatch'

      - name: Dependabot metadata
        id: metadata
        if: github.event_name == 'workflow_dispatch'
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ steps.pr_data.outputs.data.repository.pullRequest.number }}

      - name: Fetch PR data (dependabot)
        if: github.event_name != 'workflow_dispatch'
        id: pr_data_dependabot
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query ($owner: String!, $repo: String!, $prNumber: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $prNumber) {
                  author {
                    login
                  }
                  title
                  url
                }
              }
            }
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          prNumber: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependabot metadata (dependabot)
        if: github.event_name != 'workflow_dispatch'
        id: metadata_dependabot
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR data
        id: set_pr_data
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "html_url=${{ steps.pr_data.outputs.data.repository.pullRequest.url }}" >> $GITHUB_ENV
            echo "title=${{ steps.pr_data.outputs.data.repository.pullRequest.title }}" >> GITHUB_ENV
            echo "ref=${{ steps.pr_data.outputs.data.repository.pullRequest.headRefName }}" >> GITHUB_ENV
          else
            echo "html_url=${{ steps.pr_data_dependabot.outputs.data.repository.pullRequest.url }}" >> GITHUB_ENV
            echo "title=${{ steps.pr_data_dependabot.outputs.data.repository.pullRequest.title }}" >> GITHUB_ENV
            echo "ref=${{ steps.pr_data_dependabot.outputs.data.repository.pullRequest.headRefName }}" >> GITHUB_ENV
          fi

      - name: Create or checkout branch (dependabot)
        run: |
          BRANCH_NAME='topic/dependabot'
          git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"
          git pull origin ${{ env.ref }}
          git push origin "$BRANCH_NAME"
        if: github.event_name != 'workflow_dispatch'
        env:
          ref: ${{ steps.set_pr_data.outputs.ref }}

      - name: Approve & enable auto-merge for Dependabot PR
        if: |
          env.update-type == 'version-update:semver-patch' ||
          (env.update-type == 'version-update:semver-minor' && env.dependency-type == 'direct:development')
        run: |
          gh pr review --approve "$PR_URL"
          gh pr edit "$PR_URL" -t "(auto merged) $PR_TITLE"
          gh pr merge --merge "$PR_URL"
        env:
          PR_URL: ${{ env.html_url }}
          PR_TITLE: ${{ env.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
